'use strict';

const { template, standard: s } = require('./shared');

const AUTH_DATA_TEMPLATES = [
  template({
    id: 'broken-authentication',
    title: 'Broken authentication or session verification',
    severity: 'critical',
    kind: 'cdsc-http',
    summary: 'Authentication, session, JWT, or password-reset logic accepts missing, forged, replayed, or weak credentials.',
    standards: [
      s('owasp-top-10-2021', 'A07 Identification and Authentication Failures', 'https://owasp.org/Top10/en/A07_2021-Identification_and_Authentication_Failures/'),
      s('owasp-api-top-10-2023', 'API2 Broken Authentication', 'https://owasp.org/API-Security/editions/2023/en/0xa2-broken-authentication/'),
      s('cwe', 'CWE-287 Improper Authentication', 'https://cwe.mitre.org/data/definitions/287.html'),
    ],
    signals: ['JWT accepted without signature/issuer/audience check', 'password reset token is reusable or predictable', 'session cookie lacks expiration or rotation'],
    evidence: ['credential type', 'verification decision point', 'replay or forgery payload'],
    pass: ['forged, expired, missing, and replayed credentials are rejected', 'valid credential still succeeds'],
    fail: ['attacker can authenticate or reset credentials without a valid proof'],
    negativeControls: ['public anonymous endpoint', 'test-only auth bypass gated outside production'],
    fixtures: ['unsigned JWT', 'expired reset token', 'valid signed token control'],
    metrics: ['auth_bypass_block_rate', 'token_replay_block_rate'],
    fixPatterns: ['verify issuer/audience/signature', 'make reset tokens single-use and expiring', 'rotate session after privilege changes'],
  }),
  template({
    id: 'mass-assignment-bopla',
    title: 'Broken object property authorization or mass assignment',
    severity: 'high',
    summary: 'Request-controlled properties can update protected object fields such as role, tenant, price, balance, status, or owner id.',
    standards: [
      s('owasp-api-top-10-2023', 'API3 Broken Object Property Level Authorization', 'https://owasp.org/API-Security/editions/2023/en/0xa3-broken-object-property-level-authorization/'),
      s('owasp-top-10-2021', 'A01 Broken Access Control', 'https://owasp.org/Top10/en/A01_2021-Broken_Access_Control/'),
      s('cwe', 'CWE-915 Improperly Controlled Modification of Dynamically-Determined Object Attributes', 'https://cwe.mitre.org/data/definitions/915.html'),
    ],
    signals: ['req.body spread into create/update', 'ORM update receives unfiltered request object', 'hidden fields such as role/isAdmin/tenantId/price are writable'],
    evidence: ['protected property name', 'request payload', 'write target'],
    pass: ['only explicit allowlisted client fields are written', 'protected field changes are rejected or ignored'],
    fail: ['payload changes protected property or privilege-bearing field'],
    negativeControls: ['typed DTO mapped field-by-field', 'admin-only update with explicit property policy'],
    fixtures: ['isAdmin true payload', 'tenantId reassignment payload', 'allowed displayName update'],
    metrics: ['protected_property_block_rate', 'allowed_field_pass_rate'],
    fixPatterns: ['map input field-by-field', 'define per-role writable fields', 'separate internal and client DTOs'],
  }),
  template({
    id: 'excessive-data-exposure',
    title: 'Excessive sensitive data exposure in API response',
    severity: 'high',
    summary: 'API responses return secrets, private fields, internal ids, auth material, or other properties the caller should not read.',
    standards: [
      s('owasp-api-top-10-2023', 'API3 Broken Object Property Level Authorization', 'https://owasp.org/API-Security/editions/2023/en/0xa3-broken-object-property-level-authorization/'),
      s('owasp-top-10-2021', 'A01 Broken Access Control', 'https://owasp.org/Top10/en/A01_2021-Broken_Access_Control/'),
      s('cwe', 'CWE-200 Exposure of Sensitive Information', 'https://cwe.mitre.org/data/definitions/200.html'),
    ],
    signals: ['returns full ORM model/user object', 'response includes passwordHash/token/secret/internalNotes/cost/admin flags', 'GraphQL selection exposes protected field'],
    evidence: ['response serializer', 'sensitive field name', 'caller role or tenant'],
    pass: ['response is projected through explicit public schema', 'sensitive fields are absent for unauthorized callers'],
    fail: ['unauthorized caller receives sensitive or internal property'],
    negativeControls: ['owner reads own allowed profile field', 'admin endpoint with documented field policy'],
    fixtures: ['user object with passwordHash', 'billing response with internal cost', 'public projection control'],
    metrics: ['sensitive_field_leak_rate', 'projection_schema_coverage'],
    fixPatterns: ['project response allowlist', 'use public DTO serializers', 'test role-specific response schemas'],
  }),
  template({
    id: 'business-flow-abuse',
    title: 'Unrestricted access to sensitive business flow',
    severity: 'medium',
    kind: 'cdsc-http',
    summary: 'A sensitive business workflow can be automated, repeated, or sequenced in a harmful way without domain-specific controls.',
    standards: [
      s('owasp-api-top-10-2023', 'API6 Unrestricted Access to Sensitive Business Flows', 'https://owasp.org/API-Security/editions/2023/en/0xa6-unrestricted-access-to-sensitive-business-flows/'),
      s('owasp-top-10-2021', 'A04 Insecure Design', 'https://owasp.org/Top10/en/A04_2021-Insecure_Design/'),
      s('cwe', 'CWE-840 Business Logic Errors', 'https://cwe.mitre.org/data/definitions/840.html'),
    ],
    signals: ['purchase/reservation/invite/vote/comment/coupon endpoint has no quota, idempotency, or abuse control', 'workflow step can be replayed out of order'],
    evidence: ['business flow', 'abuse dimension', 'rate/quota/idempotency control'],
    pass: ['workflow enforces quota, idempotency, ordering, or risk controls appropriate to the business impact'],
    fail: ['automation can drain inventory, spam, reserve scarce resource, abuse coupons, or bypass flow order'],
    unknown: ['business sensitivity cannot be inferred from code alone', 'no workflow fixture exists to model repeated access'],
    negativeControls: ['low-impact read endpoint', 'admin batch flow with explicit operator gate'],
    fixtures: ['repeat purchase scarce item', 'coupon replay', 'idempotency-key control'],
    metrics: ['abuse_replay_block_rate', 'idempotency_enforcement_rate'],
    fixPatterns: ['add idempotency keys', 'rate-limit by actor/business object', 'encode workflow state machine'],
  }),
  template({
    id: 'insecure-deserialization',
    title: 'Unsafe deserialization of untrusted data',
    severity: 'high',
    summary: 'Untrusted serialized data is loaded through a format or parser that can instantiate objects, execute code, or mutate prototypes.',
    standards: [
      s('owasp-top-10-2021', 'A08 Software and Data Integrity Failures', 'https://owasp.org/Top10/en/A08_2021-Software_and_Data_Integrity_Failures/'),
      s('cwe', 'CWE-502 Deserialization of Untrusted Data', 'https://cwe.mitre.org/data/definitions/502.html'),
    ],
    signals: ['deserialize/unserialize/load of request data', 'yaml load with unsafe schema', 'prototype-bearing JSON merged into objects'],
    evidence: ['serialized payload source', 'parser/deserializer', 'reachable object/code side effect'],
    pass: ['untrusted data uses safe parser and schema validation', 'prototype/object construction gadgets are blocked'],
    fail: ['payload triggers code execution, object gadget, prototype pollution, or privileged state mutation'],
    negativeControls: ['JSON.parse followed by strict schema', 'trusted signed internal cache payload'],
    fixtures: ['unsafe YAML tag payload', '__proto__ pollution payload', 'schema-validated JSON control'],
    metrics: ['gadget_payload_block_rate', 'prototype_pollution_block_rate'],
    fixPatterns: ['avoid object deserialization for untrusted data', 'use safe parser schema', 'validate and freeze decoded shape'],
  }),
  template({
    id: 'llm-output-to-sensitive-sink',
    title: 'LLM output reaches sensitive sink without validation',
    severity: 'high',
    kind: 'agent-permission',
    summary: 'Generated text or tool output is used as code, shell, HTML, SQL, policy, or external action input without deterministic validation.',
    standards: [
      s('owasp-llm-top-10-2025', 'LLM05 Improper Output Handling', 'https://genai.owasp.org/llmrisk/llm052025-improper-output-handling/'),
      s('owasp-top-10-2021', 'A03 Injection', 'https://owasp.org/Top10/en/A03_2021-Injection/'),
      s('cwe', 'CWE-20 Improper Input Validation', 'https://cwe.mitre.org/data/definitions/20.html'),
    ],
    signals: ['LLM completion passed to eval/exec/shell/innerHTML/query/send/delete', 'agent plan auto-executes generated command'],
    evidence: ['generated output source', 'sink/action', 'validation or approval gate'],
    pass: ['LLM output is parsed as constrained data and validated before sink use', 'dangerous action requires deterministic policy or human confirmation'],
    fail: ['generated payload executes code, mutates files, sends external action, or changes policy without validation'],
    negativeControls: ['LLM output displayed as escaped text', 'schema-constrained JSON used for read-only search'],
    fixtures: ['generated shell command injection', 'generated HTML script payload', 'validated JSON control'],
    metrics: ['unsafe_generated_action_block_rate', 'schema_validation_pass_rate'],
    fixPatterns: ['constrain output schema', 'validate before sink', 'separate generation from execution approval'],
  }),
  template({
    id: 'llm-data-model-poisoning',
    title: 'Training, fine-tuning, model, or embedding data poisoning',
    severity: 'high',
    kind: 'agent-permission',
    summary: 'Untrusted data can alter model or retrieval behavior through poisoned training/fine-tuning data, model artifacts, embeddings, or adapters.',
    standards: [
      s('owasp-llm-top-10-2025', 'LLM04 Data and Model Poisoning', 'https://genai.owasp.org/llmrisk/llm042025-data-and-model-poisoning/'),
      s('owasp-llm-top-10-2025', 'LLM03 Supply Chain', 'https://genai.owasp.org/llmrisk/llm032025-supply-chain/'),
      s('cwe', 'CWE-345 Insufficient Verification of Data Authenticity', 'https://cwe.mitre.org/data/definitions/345.html'),
    ],
    signals: ['training/fine-tuning/RAG ingestion accepts unverified source', 'model artifact loaded without provenance/hash/signature', 'dataset change lacks origin and review evidence'],
    evidence: ['data/model source', 'provenance or hash state', 'behavioral trigger or poisoned sample'],
    pass: ['data/model artifacts have provenance, integrity, review, and rollback evidence', 'poisoned samples are rejected or isolated'],
    fail: ['unverified artifact or dataset can introduce biased, malicious, or backdoored behavior'],
    unknown: ['model behavior cannot be evaluated with available fixture', 'provenance metadata is incomplete'],
    negativeControls: ['curated signed dataset', 'hash-pinned model artifact'],
    fixtures: ['poisoned fine-tuning sample', 'unsigned model adapter', 'signed dataset control'],
    metrics: ['provenance_required_rate', 'poison_sample_rejection_rate'],
    fixPatterns: ['track ML-BOM/provenance', 'verify artifact hashes/signatures', 'red-team poisoned samples before promotion'],
  }),
  template({
    id: 'llm-misinformation-critical-decision',
    title: 'LLM misinformation used for critical decision',
    severity: 'medium',
    kind: 'agent-permission',
    summary: 'An LLM answer can drive security, legal, medical, financial, or operational decisions without grounding, validation, or human review.',
    standards: [
      s('owasp-llm-top-10-2025', 'LLM09 Misinformation', 'https://genai.owasp.org/llmrisk/llm092025-misinformation/'),
      s('owasp-top-10-2021', 'A04 Insecure Design', 'https://owasp.org/Top10/en/A04_2021-Insecure_Design/'),
      s('cwe', 'CWE-20 Improper Input Validation', 'https://cwe.mitre.org/data/definitions/20.html'),
    ],
    signals: ['LLM output controls recommendation/approval/diagnosis/security decision', 'no citation/grounding/verification/human-review boundary'],
    evidence: ['decision type', 'grounding source', 'validation or review gate'],
    pass: ['critical claim is grounded, cited, bounded, and independently verified before action'],
    fail: ['fabricated or unsupported claim can trigger critical decision or user-visible advice as fact'],
    unknown: ['decision criticality is unclear', 'truth fixture or authoritative source is unavailable'],
    negativeControls: ['creative drafting with no decision side effect', 'answer clearly labeled unverified and blocked from action'],
    fixtures: ['hallucinated package recommendation', 'unsupported legal/medical claim', 'grounded citation control'],
    metrics: ['unsupported_claim_block_rate', 'grounding_required_rate'],
    fixPatterns: ['require citations from trusted sources', 'separate advice from execution', 'route high-impact decisions to human review'],
  }),
];

module.exports = { AUTH_DATA_TEMPLATES };
