'use strict';

const { template, standard: s } = require('./shared');

const WEB_TEMPLATES = [
  template({
    id: 'missing-authz',
    title: 'Sensitive route without authorization guard',
    severity: 'high',
    kind: 'cdsc-http',
    summary: 'A privileged route is reachable without an explicit authn/authz middleware or policy check.',
    standards: [
      s('owasp-top-10-2021', 'A01 Broken Access Control', 'https://owasp.org/Top10/en/A01_2021-Broken_Access_Control/'),
      s('owasp-api-top-10-2023', 'API5 Broken Function Level Authorization', 'https://owasp.org/API-Security/editions/2023/en/0xa5-broken-function-level-authorization/'),
      s('cwe', 'CWE-862 Missing Authorization', 'https://cwe.mitre.org/data/definitions/862.html'),
    ],
    signals: ['Express/Router route with admin|billing|users|account path', 'no requireAuth/authorize/role middleware in route chain'],
    evidence: ['HTTP method and route path', 'baseline unauthenticated replay response', 'fixed replay response'],
    pass: ['baseline unauthenticated request fails the contract', 'fixed replay returns 401 or 403', 'source line and replay subject match'],
    fail: ['same unauthenticated replay reaches protected data or action', 'fixed replay still returns 2xx/3xx for protected route'],
    negativeControls: ['public health/readme route without sensitive path', 'route guarded by requireAuth or role middleware'],
    fixtures: ['vulnerable admin route returning 200', 'fixed same route returning 401', 'public route returning 200'],
    metrics: ['baseline_fixed_replay_delta_ms', 'runtime_flake_rate'],
    fixPatterns: ['add authentication middleware', 'enforce object/function authorization before handler logic'],
  }),
  template({
    id: 'idor-bola',
    title: 'Broken object level authorization',
    severity: 'high',
    kind: 'cdsc-http',
    summary: 'A request-controlled object id is used to fetch another tenant or user object without ownership enforcement.',
    standards: [
      s('owasp-top-10-2021', 'A01 Broken Access Control', 'https://owasp.org/Top10/en/A01_2021-Broken_Access_Control/'),
      s('owasp-api-top-10-2023', 'API1 Broken Object Level Authorization', 'https://owasp.org/API-Security/editions/2023/en/0xa1-broken-object-level-authorization/'),
      s('cwe', 'CWE-863 Incorrect Authorization', 'https://cwe.mitre.org/data/definitions/863.html'),
    ],
    signals: ['req.params.id or req.query.id used in data lookup', 'no owner/tenant predicate in query or post-fetch check'],
    evidence: ['actor identity', 'victim object id', 'object ownership expectation'],
    pass: ['attacker actor receives 401/403/404 for victim object', 'authorized owner still receives expected object'],
    fail: ['attacker actor receives victim object or mutates it'],
    unknown: ['ownership model cannot be inferred', 'fixture lacks two distinct actors or tenants'],
    negativeControls: ['self-owned object access', 'admin-only path with explicit role check'],
    fixtures: ['two users with separate records', 'attacker requests victim id', 'owner requests own id'],
    metrics: ['cross_actor_replay_count', 'authorization_matrix_coverage'],
    fixPatterns: ['scope queries by authenticated subject', 'centralize object authorization policy'],
  }),
  template({
    id: 'removed-security-guard',
    title: 'Authentication, authorization, or validation guard removed',
    severity: 'high',
    summary: 'A diff removes an existing security gate without equivalent replacement in the same change.',
    standards: [
      s('owasp-top-10-2021', 'A01 Broken Access Control', 'https://owasp.org/Top10/en/A01_2021-Broken_Access_Control/'),
      s('owasp-api-top-10-2023', 'API5 Broken Function Level Authorization', 'https://owasp.org/API-Security/editions/2023/en/0xa5-broken-function-level-authorization/'),
      s('cwe', 'CWE-862 Missing Authorization', 'https://cwe.mitre.org/data/definitions/862.html'),
    ],
    signals: ['removed req.user/requireAuth/authorize/validate/schema.parse line', 'no replacement guard in added lines nearby'],
    evidence: ['removed guard text', 'affected route/function', 'replacement analysis'],
    pass: ['replacement guard is present and equivalent or stronger', 'tests prove unauthorized actor is rejected'],
    fail: ['guard removed and protected flow remains reachable'],
    negativeControls: ['renamed guard with same semantics', 'dead-code deletion with no reachable route'],
    fixtures: ['diff removing requireAuth', 'diff replacing requireAuth with requireRole', 'diff deleting unused helper'],
    metrics: ['nearby_replacement_detection_rate'],
    fixPatterns: ['restore guard', 'replace with centralized policy and regression test'],
  }),
  template({
    id: 'sql-injection',
    title: 'SQL query built with attacker-controlled string interpolation',
    severity: 'high',
    summary: 'User-controlled input is concatenated or interpolated into SQL text before query execution.',
    standards: [
      s('owasp-top-10-2021', 'A03 Injection', 'https://owasp.org/Top10/en/A03_2021-Injection/'),
      s('owasp-api-top-10-2023', 'API8 Security Misconfiguration', 'https://owasp.org/API-Security/editions/2023/en/0xa8-security-misconfiguration/'),
      s('cwe', 'CWE-89 SQL Injection', 'https://cwe.mitre.org/data/definitions/89.html'),
    ],
    signals: ['query/execute/raw call', 'SELECT/INSERT/UPDATE/DELETE string contains + or template interpolation', 'req.* or process.argv reaches query'],
    evidence: ['query text', 'input source', 'database execution call'],
    pass: ['query uses parameters/bind variables or ORM predicate API', 'malicious input remains data not syntax'],
    fail: ['payload changes query structure or bypasses predicate'],
    negativeControls: ['constant query string', 'parameterized query with placeholders and values array'],
    fixtures: ['login bypass payload', 'tenant filter bypass payload', 'parameterized equivalent'],
    metrics: ['payload_block_rate'],
    fixPatterns: ['parameterize query', 'use ORM query builder without raw interpolation'],
  }),
  template({
    id: 'nosql-injection',
    title: 'NoSQL selector or operator injection',
    severity: 'high',
    summary: 'Untrusted object input is merged into Mongo/NoSQL filters and can introduce operators such as $ne or $where.',
    standards: [
      s('owasp-top-10-2021', 'A03 Injection', 'https://owasp.org/Top10/en/A03_2021-Injection/'),
      s('owasp-api-top-10-2023', 'API8 Security Misconfiguration', 'https://owasp.org/API-Security/editions/2023/en/0xa8-security-misconfiguration/'),
      s('cwe', 'CWE-943 Improper Neutralization of Special Elements in Data Query Logic', 'https://cwe.mitre.org/data/definitions/943.html'),
    ],
    signals: ['find/findOne/update with req.body or spread object', 'Mongo operator keys from request body'],
    evidence: ['filter object', 'operator-bearing payload', 'collection/query call'],
    pass: ['input is allowlisted to scalar fields', 'operator keys are rejected before query'],
    fail: ['payload with $ne/$gt/$where alters query semantics'],
    negativeControls: ['typed DTO mapped field-by-field', 'schema validation strips unknown operators'],
    fixtures: ['login with password {$ne:null}', 'safe scalar mapping'],
    metrics: ['operator_payload_rejection_rate'],
    fixPatterns: ['map allowed fields explicitly', 'reject keys starting with $ or containing dot'],
  }),
  template({
    id: 'shell-injection',
    title: 'OS command execution with attacker-controlled argument',
    severity: 'high',
    summary: 'External input reaches shell execution or command arguments without safe argv separation and allowlisting.',
    standards: [
      s('owasp-top-10-2021', 'A03 Injection', 'https://owasp.org/Top10/en/A03_2021-Injection/'),
      s('owasp-cheat-sheet', 'OS Command Injection Defense', 'https://cheatsheetseries.owasp.org/cheatsheets/OS_Command_Injection_Defense_Cheat_Sheet.html'),
      s('cwe', 'CWE-78 OS Command Injection', 'https://cwe.mitre.org/data/definitions/78.html'),
    ],
    signals: ['exec/execSync with string concat or template interpolation', 'child_process shell option true', 'req.* or process.argv in command'],
    evidence: ['command string or argv', 'input source', 'shell metacharacter payload'],
    pass: ['no shell string is constructed from input', 'argv is separated and input is allowlisted'],
    fail: ['payload executes additional command or changes command meaning'],
    negativeControls: ['spawnFile with fixed executable and bounded args', 'library API instead of shell command'],
    fixtures: ['filename payload with semicolon', 'safe argv command'],
    metrics: ['metacharacter_payload_block_rate'],
    fixPatterns: ['avoid shell', 'use execFile/spawn with argv', 'validate against command-specific allowlist'],
  }),
  template({
    id: 'path-traversal',
    title: 'User-controlled filesystem path escapes project boundary',
    severity: 'high',
    summary: 'Untrusted path segments are joined into filesystem paths without normalization and root containment checks.',
    standards: [
      s('owasp-top-10-2021', 'A01 Broken Access Control', 'https://owasp.org/Top10/en/A01_2021-Broken_Access_Control/'),
      s('cwe', 'CWE-22 Path Traversal', 'https://cwe.mitre.org/data/definitions/22.html'),
    ],
    signals: ['path.join with req.params/req.query/process.argv', 'fs read/write after unresolved user path'],
    evidence: ['base directory', 'user path segment', 'resolved path'],
    pass: ['resolved realpath stays under expected root', 'traversal and symlink escapes are rejected'],
    fail: ['../ or symlink path reads/writes outside allowed root'],
    negativeControls: ['static asset path under root', 'allowlisted filename without separators'],
    fixtures: ['../../.env read attempt', 'symlink escape', 'safe file under root'],
    metrics: ['escape_payload_block_rate'],
    fixPatterns: ['resolve and compare realpath prefix', 'reject absolute paths and traversal segments'],
  }),
  template({
    id: 'unsafe-file-mutation',
    title: 'User-controlled file write or delete',
    severity: 'high',
    summary: 'A request or CLI parameter controls a write/delete target without a safe root and operation policy.',
    standards: [
      s('owasp-top-10-2021', 'A01 Broken Access Control', 'https://owasp.org/Top10/en/A01_2021-Broken_Access_Control/'),
      s('cwe', 'CWE-73 External Control of File Name or Path', 'https://cwe.mitre.org/data/definitions/73.html'),
    ],
    signals: ['fs.writeFile/rm/unlink with req.* or process.argv', 'mutation under security or config paths'],
    evidence: ['operation type', 'target path', 'actor/source of path'],
    pass: ['mutation target is derived from server-side id or allowlist', 'protected paths are blocked'],
    fail: ['attacker controls target file outside intended write area'],
    negativeControls: ['server-generated temp file name', 'append to fixed audit log through safe logger'],
    fixtures: ['delete arbitrary file attempt', 'write protected security evidence attempt', 'safe upload name'],
    metrics: ['protected_path_block_rate'],
    fixPatterns: ['server-generate storage keys', 'use safe path resolver and operation allowlist'],
  }),
  template({
    id: 'ssrf',
    title: 'Server-side request forgery',
    severity: 'high',
    summary: 'A server-side HTTP client can be directed by user input to internal, metadata, localhost, or link-local targets.',
    standards: [
      s('owasp-top-10-2021', 'A10 SSRF', 'https://owasp.org/Top10/en/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/'),
      s('owasp-api-top-10-2023', 'API7 SSRF', 'https://owasp.org/API-Security/editions/2023/en/0xa7-server-side-request-forgery/'),
      s('owasp-cheat-sheet', 'SSRF Prevention', 'https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html'),
      s('cwe', 'CWE-918 SSRF', 'https://cwe.mitre.org/data/definitions/918.html'),
    ],
    signals: ['fetch/axios/got/request with req.* URL', 'webhook/import/proxy URL fields', 'redirect following enabled'],
    evidence: ['requested URL', 'DNS/IP classification', 'redirect behavior'],
    pass: ['URL target is validated as public/allowed', 'redirects cannot reach private networks'],
    fail: ['payload reaches localhost, private range, cloud metadata, or file scheme'],
    negativeControls: ['fixed upstream base URL', 'allowlisted partner domain with DNS/IP checks'],
    fixtures: ['169.254.169.254 URL', 'localhost URL', 'safe public allowlisted URL'],
    metrics: ['private_ip_block_rate', 'redirect_bypass_block_rate'],
    fixPatterns: ['accept IDs/domains not arbitrary URLs', 'resolve and block private/link-local addresses', 'disable redirects'],
  }),
  template({
    id: 'open-redirect',
    title: 'User-controlled redirect target',
    severity: 'medium',
    summary: 'A redirect destination comes from request input and can send users to an attacker-controlled site.',
    standards: [
      s('owasp-top-10-2021', 'A01 Broken Access Control', 'https://owasp.org/Top10/en/A01_2021-Broken_Access_Control/'),
      s('cwe', 'CWE-601 Open Redirect', 'https://cwe.mitre.org/data/definitions/601.html'),
    ],
    signals: ['res.redirect(req.query.next/url)', 'Location header built from request input'],
    evidence: ['redirect parameter', 'allowed destination policy', 'observed Location header'],
    pass: ['redirect target is relative or allowlisted', 'external attacker URL is rejected'],
    fail: ['attacker URL appears in Location header'],
    negativeControls: ['fixed redirect path', 'relative path validated to same origin'],
    fixtures: ['https://attacker.example redirect', '/dashboard redirect'],
    metrics: ['external_redirect_block_rate'],
    fixPatterns: ['map redirect keys to server-side destinations', 'allow only relative same-origin paths'],
  }),
  template({
    id: 'xss-unsafe-html',
    title: 'Untrusted HTML rendered without sanitization',
    severity: 'high',
    summary: 'User or LLM-controlled content is inserted into HTML/DOM sinks such as innerHTML or dangerouslySetInnerHTML.',
    standards: [
      s('owasp-top-10-2021', 'A03 Injection', 'https://owasp.org/Top10/en/A03_2021-Injection/'),
      s('cwe', 'CWE-79 Cross-site Scripting', 'https://cwe.mitre.org/data/definitions/79.html'),
    ],
    signals: ['dangerouslySetInnerHTML', 'innerHTML assignment', 'template rendering with unescaped user content'],
    evidence: ['HTML sink', 'untrusted content source', 'script/event-handler payload'],
    pass: ['content is escaped or sanitized by reviewed policy', 'script/event payload remains inert'],
    fail: ['payload executes script or injects event handler/URL JavaScript'],
    negativeControls: ['static trusted markup', 'sanitized markdown renderer with tests'],
    fixtures: ['img onerror payload', 'safe escaped text', 'trusted static markup'],
    metrics: ['payload_neutralization_rate'],
    fixPatterns: ['escape by default', 'sanitize with allowlist', 'avoid raw HTML sinks'],
  }),
  template({
    id: 'csrf-missing-token',
    title: 'State-changing browser request without CSRF defense',
    severity: 'medium',
    summary: 'Cookie-authenticated state-changing endpoints accept cross-site requests without token or SameSite defense.',
    standards: [
      s('owasp-top-10-2021', 'A01 Broken Access Control', 'https://owasp.org/Top10/en/A01_2021-Broken_Access_Control/'),
      s('owasp-cheat-sheet', 'CSRF Prevention', 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html'),
      s('cwe', 'CWE-352 CSRF', 'https://cwe.mitre.org/data/definitions/352.html'),
    ],
    signals: ['POST/PUT/PATCH/DELETE route uses cookie session', 'no csrf token/origin check/SameSite policy nearby'],
    evidence: ['state-changing method', 'auth mechanism', 'CSRF mitigation presence'],
    pass: ['cross-site request lacks valid token and is rejected', 'same-site valid token request succeeds'],
    fail: ['cross-site form/request performs state change'],
    negativeControls: ['bearer-token API not using ambient cookies', 'read-only GET endpoint'],
    fixtures: ['cookie-auth POST without token', 'POST with valid token', 'bearer API control'],
    metrics: ['cross_site_mutation_block_rate'],
    fixPatterns: ['synchronizer/double-submit token', 'Origin/Referer validation', 'SameSite cookies'],
  }),
];

module.exports = { WEB_TEMPLATES };
